# Generated by Django 4.1.3 on 2022-11-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blog_options_alter_people_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Дата рождения (xx.xx.xxxx)',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='Должность',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='ФИО',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='+7xxxxxxxxxx (без пробельно)',
            new_name='whatsapp_number',
        ),
    ]
