# Generated by Django 4.1.3 on 2022-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blog_options_alter_people_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='+7xxxxxxxxxx (без пробельно)',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Дата рождения (xx.xx.xxxx)',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Должность',
        ),
        migrations.RemoveField(
            model_name='people',
            name='ФИО',
        ),
        migrations.AddField(
            model_name='people',
            name='birthday',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='whatsapp_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
