# Generated by Django 4.1.3 on 2022-12-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_people_+7xxxxxxxxxx (без пробельно)_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='whatsapp_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='people',
            name='birthday',
        ),
    ]
