# Generated by Django 4.1.3 on 2022-12-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_whatsapp_number_people_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('discount_percent', models.CharField(max_length=4)),
                ('picture', models.ImageField(blank=True, upload_to='media/bonus')),
            ],
            options={
                'verbose_name': 'Бонусный сертификат',
                'verbose_name_plural': 'Бонусные сертификаты',
            },
        ),
    ]
